name: Publish Package

on:
  push:
    branches: [main, next]

jobs:
  publish:

    uses: crealgo/hotcakes-ci/.github/workflows/semantic-release.yaml@main
    secrets:
      GITHUB_TOKEN: ${{ secrets.CREALGO_GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.CREALGO_NPM_TOKEN }}
