name: Publish Package

on:
  push:
    branches: [main, next]

jobs:
  publish:
    uses: crealgo/hotcakes-ci/.github/workflows/semantic-release.yaml@main
    secrets:
      npm-token: ${{ secrets.CREALGO_NPM_TOKEN }}
      gh-token: ${{ secrets.GITHUB_TOKEN }}
